# If a prefix of an imported package name doesn't match any name written in an array,
# assertion will be failed.

# Packages which can be imported from ui package
"github.com/tomoemon/assert-dep/sampleProject/ui" = [
    # As there are dependencies from ui, assertion will be failed
]

# Packages which can be imported from infra package
"github.com/tomoemon/assert-dep/sampleProject/infra" = [
    "github.com/tomoemon/assert-dep/sampleProject/domain",
    "github.com/tomoemon/assert-dep/sampleProject/infra",
]

# Packages which can be imported from domain package
"github.com/tomoemon/assert-dep/sampleProject/domain" = [
    "github.com/tomoemon/assert-dep/sampleProject/domain",
]
