# project root path from $GOROOT/src. eg. "github.com/tomoemon/impas"
root = "github.com/tomoemon/impas/docs/exampleProjects"

# ignore imported packages NOT includend in the root project if true
ignoreOther = true

# search imported packages recursively if true
recursive = false

# If a prefix of an imported package name doesn't match any name written in an array,
# assertion will be failed.

# Packages which can be imported from ui package
# You can write a path relatively from the project root
# Or write a path absolutely from the $GOPATH/src
[[constraint]]
from = "github.com/tomoemon/impas/docs/exampleProjects/ui"
allow = [
    # As there are dependencies from ui, assertion will be failed
]

# Packages which can be imported from infra package
[[constraint]]
from = "./infra"
allow = [
    "./domain",
    "./infra",
]

# Packages which can be imported from domain package
[[constraint]]
from = "github.com/tomoemon/impas/docs/exampleProjects/domain"
allow = [
    "github.com/tomoemon/impas/docs/exampleProjects/domain",
]
