# If a prefix of an imported package name doesn't match any name written in an array,
# assertion will be failed.

# Packages which can be imported from ui package
# You can write a path relatively from the project root
# Or write a path absolutely from the $GOPATH/src
"github.com/tomoemon/impas/docs/exampleProjects/ui" = [
    # As there are dependencies from ui, assertion will be failed
]

# Packages which can be imported from infra package
"./infra" = [
    "./domain",
    "./infra",
]

# Packages which can be imported from domain package
"github.com/tomoemon/impas/docs/exampleProjects/domain" = [
    "github.com/tomoemon/impas/docs/exampleProjects/domain",
]
